services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app 

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd:/usr/share/nginx/html